sonar.projectKey=AleksandrZimin_qa-auto-engineer-javascript-project-44
sonar.organization=aleksandrzimin
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8